### ISSUE TITLE
`RetryFact` fails even if test case succeeds after a retry

### ISSUE THREAD

**Issue by bastbu** [Azure/iotedge-lorawan-starterkit#1538]
## Expected Behavior

If for a test annotated with `RetryFact` it succeeds after a given retry, the test should succeed.

## Current Behavior

If for a test annotated with `RetryFact` it succeeds after a given retry (e.g. 2 failures and 1 success), the test is considered a failure. This will make failing E2E tests run longer, while at the end the E2E run is still considered a failed run even though one of the retries succeeded. We should consider:

- Removing the `RetryFact` attribute
- Finding a way to make sure that a retry will make the test a "success"

## Steps to Reproduce

https://github.com/Azure/iotedge-lorawan-starterkit/runs/5304413528?check_suite_focus=true

**Comment by p-schuler** [comment]
This is actually by design. The RetryFact is designed to help understand if a test passes after a retry but does not take away the duty to actually check the test and validate the root cause. Retrying tests in general is not a good idea as it tends to hide problems (like races). With LoRaWAN and the transmission over the air, it helps understanding certain problems (like not picking up a message) if they are retried. The idea is to identify those quickly and re-run the particular test area.
