### ISSUE TITLE
Wrong manifest creation in release pipeline

### ISSUE THREAD

**Issue by danigian** [Azure/iotedge-lorawan-starterkit#2045]
Our current release pipeline is overriding the generic manifest for the newly created version each time the jobs are executed for the matrix.

This should be fixed to only execute once a command like the following

```
docker manifest create  loraedge/lorawannetworksrvmodule:2.2.1 loraedge/lorawannetworksrvmodule:2.2.1-arm32v7 loraedge/lorawannetworksrvmodule:2.2.1-arm64v8 loraedge/lorawannetworksrvmodule:2.2.1-amd64 --amend
```

Wrong code:
https://github.com/Azure/iotedge-lorawan-starterkit/blob/428e220f9b89e291fdee4451fe223c55b2a06a3e/.github/workflows/create_release.yaml#L39-L42

**Comment by ouphi** [comment]
@danigian Closing this issue as this was fixed in this PR: https://github.com/Azure/iotedge-lorawan-starterkit/pull/2108

This is what we have now:
![Screenshot 2023-11-01 at 11 23 25](https://github.com/Azure/iotedge-lorawan-starterkit/assets/17216799/b0c68a3f-ea54-407a-9cc1-e98e75b445ed)

![Screenshot 2023-11-01 at 11 16 40](https://github.com/Azure/iotedge-lorawan-starterkit/assets/17216799/1e8eac2e-1cf2-4f2d-b8bd-e0f655c6a240)
