### ISSUE TITLE
Fix unobserved task execution

### ISSUE THREAD

**Issue by p-schuler** [Azure/iotedge-lorawan-starterkit#557]
We have a few instances where we fire async tasks and don't observe the result. The default behavior in .NET >= 4.5 has changed to not crash the process for unobserved task exceptions. Hence, those will go un-noticed. 

## Expected Behavior

At least log the exceptions when they are happening, if we decide not to observe the result of a task.

## Current Behavior

When a task is not observed, any exceptions that might get thrown, are not logged.

## Steps to Reproduce

```c#
_ = Task.Run(() => throw new Exception("unhandled exception"));
await Task.Delay(500);
```

**Comment by spygi** [comment]
Got bitten by this one while trying to fix broken integration tests: because calls are not observed, tests either don't fail or fail with a random assertion error which makes it hard to debug (need to step through the code). Not sure if we want to reopen this or prioritize to observe calls.
/cc @p-schuler and @bastbu since it was discussed with him
